docs/resources/build.md, internal/provider/build.go, internal/provider/resource_build.go, internal/provider/resource_build_test.go
:gift: These are surfaced via a new output `sboms` which is a map from the image digest to it's SBOM.
depends on https://github.com/chainguard-dev/terraform-provider-apko/pull/42
/kind feature
=> Feature: Add support for emitting SBOMs

docs/resources/build.md, internal/provider/build.go, internal/provider/config_data_source.go, internal/provider/reflect.go, internal/provider/reflect_test.go, internal/provider/resource_build.go, internal/provider/resource_build_test.go
:gift: This changes the type of `apko_build.config` to take the schematized APKO config.
Users can now pass a structured APKO configuration directly to `apko_build` or load it via `apko_config` and pass it through.
🚨  THIS IS A BREAKING CHANGE 🚨 
WIP until https://github.com/chainguard-dev/terraform-provider-apko/pull/51 merges
/kind feature
=> Feature: Have `apko_build` take the loaded `apko_config`

go.mod, go.sum, internal/provider/build.go, internal/provider/config_data_source.go, internal/provider/config_data_source_test.go
:gift: This changes the structured output of `apko_config` to resolve the transitive dependencies in the `apko.yaml` configuration as much as possible for consistency across the target architectures.
For example, if a user config specifies the following:
```yaml
contents:
packages:
- ca-certificates-bundle
- tzdata
- wolfi-baselayout
```
The resolved configuration might look like:
```yaml
contents:
packages:
- ca-certificates-bundle=20230506-r0
- glibc-locale-posix=2.37-r6
- tzdata=2023c-r0
- wolfi-baselayout=20230201-r0
```
If there are packages that resolve inconsistently across architectures, we will either preserve their input constraint (if a direct dependency) or elide it (if a transitive dependency).
This change allows us to do interesting things like attest to the locked …
=> Feature: Have `apko_config` "lock" the configuration as much as it can.

README.md, docs/index.md, internal/provider/build.go, internal/provider/config_data_source.go, internal/provider/config_data_source_test.go, internal/provider/provider.go
:broom: This renames the provider-level fields to qualify them in ways that better convey their semantics contributing to the `apko_config`.
🚨 THIS IS A BREAKING CHANGE 🚨 
/kind cleanup
=> Cleanup: Rename the provider-level fields to increase clarity.

docs/data-sources/config.md, internal/provider/config_data_source.go, internal/provider/config_data_source_test.go, internal/provider/resource_build_test.go
This `apko_config`:
```
data "apko_config" "this" {
config_contents = <<EOF
contents:
packages:
- ca-certificates-bundle=20230506-r0
- glibc-locale-posix=2.37-r6
EOF
extra_packages = ["tzdata=2023c-r0"]
}
```
...produces an output config that has `tzdata` added to it. This lets us inject packages to produce a `-dev` variant.
=> apko_config: add extra_packages

docs/data-sources/config.md, docs/index.md, internal/provider/config_data_source.go, internal/provider/config_data_source_test.go, internal/provider/provider.go
`default_annotations` feels like a more accurate description than `extra`, like `default_archs`.
The precedence is YAML config > datasource config > provider config
=> rename extra_annotations -> default_annotations, add provider support

go.mod, go.sum, internal/provider/provider.go, internal/provider/resource_build.go
Each of the remote.Write[Index] calls has to do a Ping and a Token request, which increases the number of requests we send by quite a lot.
Instead, this uses remote.Pusher, so we can reuse ping results and authenticated context.
=> Take advantage of remote.Reuse

internal/provider/config_data_source.go
fixes the panic by defaulting to the `host` arch. though another valid soln is to raise an error message if we want that to be the default behavior!
fixes https://github.com/chainguard-dev/terraform-provider-apko/issues/63
=> default to host arch when nothing is specified

.github/workflows/test.yml, internal/provider/build.go, internal/provider/config_data_source.go
I tried running with `-race` and some tests still fail due to stuff in `go-apk`'s memfs.
This at least should fix the concurrent map writes, and another easy one I found running with `-race`.
Fixes #102
=> fix some data races

docs/data-sources/config.md, docs/data-sources/tags.md, docs/resources/build.md, go.mod, go.sum, internal/provider/build.go, internal/provider/resource_build_test.go
These changes allow builds from `apko_build` to be reproduced by feeding an attestation of the `apko_config` through `apko publish`.
=> Quiet the noise to allow reproducing builds from attestations.

internal/provider/config_data_source.go, internal/provider/config_data_source_test.go
Currently when we are performing package builds, we will be unable to lock a package version across architectures and we surface a mediocre warning, and the not-fully-locked configuration creates errors downstream when we try to create things like SLSA attestations or extract version tags because things are not fully resolved.
By promoting this to an error, we make things fail earlier and with a (now much) clearer error message.
=> Make failure to unify a specified package an error.

internal/provider/config_data_source_test.go
glibc-locale-posix is no longer a dependency of wolfi-baselayout: https://github.com/wolfi-dev/os/commit/5c347faa85567977afc55ee5d06b5b74c4fa06cd
=> Fix transitive dependency test

.github/workflows/mega-module.yaml
Update images digests
```release-note
NONE
```
=> Update images digests

.github/workflows/mega-module.yaml, .github/workflows/test.yml, go.mod, internal/provider/config_data_source.go, internal/provider/config_data_source_test.go
There are some cases in the images repo, which will now result in an error:
```
│ Error: Unable to parse apko configuration
│ 
│   with module.dotnet.module.sdk-config.data.apko_config.this,
│   on images/dotnet/configs/sdk/main.tf line 12, in data "apko_config" "this":
│   12: data "apko_config" "this" {
│ 
│ yaml: unmarshal errors:
│   line 14: field recursive not found in type types.ImageAccounts
```
```
git grep "^  recursive:" | wc -l
41
```
There may be other cases where we're doing this.
=> parse YAML strictly, failing on unknown fields

.gitignore, internal/provider/config_data_source.go
```
TF_APKO_OUT_DIR=$(pwd) TF_ACC=1 go test ./internal/provider/... -count=1
```
<details>
<summary>10df20.pre.apko.json</summary>
```
{
"contents": {
"repositories": [
"https://packages.wolfi.dev/os"
],
"keyring": [
"https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"
],
"packages": [
"ca-certificates-bundle",
"tzdata",
"wolfi-baselayout"
]
},
"entrypoint": {},
"accounts": {
"run-as": "65532",
"users": [
{
"username": "nonroot",
"uid": 65532,
"gid": 65532
}
],
"groups": [
{
"groupname": "nonroot",
"gid": 65532
}
]
},
"archs": [
"amd64",
"arm64"
],
"os-release": {}
}
```
</details>
<details>
<summary>10df20.post.apko.json</summary>
```
{
"contents": {
"repositories": [
"https://packages.wolfi.dev/os"
],
"keyring": [
"https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"
],
"packages": [ …
```
=> support writing pre- and post-resolved configs to disk

internal/provider/config_data_source.go
We were getting hash collisions (and files overwritten) for configs that had the same base input but had different extra flags passed in.
=> Fix hash we use for apko resolver input

.github/workflows/digestabot.yaml, .github/workflows/release.yml
This reduces the digestabot permissions to reflect the use of a PAT, and adds explicit permissions to the release workflow.
=> Audit the permissions on workflows.

internal/provider/tags_data_source.go
From
```
╷
│ Error: Unable to find package
│
│   with module.keda.module.versioned["keda-2.13"].data.apko_tags.tags[0],
│   on tflib/publisher/main.tf line 189, in data "apko_tags" "tags":
│  189: data "apko_tags" "tags" {
│
│ Unable to find package: keda-2.13
╵
```
To
```
╷
│ Error: Unable to find package: keda-2.13...
│
│   with module.keda.module.versioned["keda-2.13"].data.apko_tags.tags[0],
│   on tflib/publisher/main.tf line 189, in data "apko_tags" "tags":
│  189: data "apko_tags" "tags" {
│
│ ...in package list:
│       busybox=1.36.1-r8
│       ca-certificates-bundle=20240315-r1
│       chainguard-baselayout=20230214-r6
│       glibc=2.39-r3
│       glibc-locale-posix=2.39-r3
│       keda-2.14=2.14.0-r0
│       keda-2.14-compat=2.14.0-r0
│       ld-linux=2.39-r3
│ …
```
=> Improve unable to find package error message

internal/provider/tags_data_source.go, internal/provider/tags_data_source_test.go
Today sometimes configs request some package, say, `nodejs`, which gets provided by a package named `nodejs-21`. When it comes time to get the tags for this config, we can't pass `nodejs` today because the resulting config has no package with that name. And callers don't necessarily know it's called `nodejs-21`, or else they would have requested that.
This makes `apko_tags` aware of this scenario and slightly less dumb, and if it can't find a package named `nodejs`, will look for a package named `nodejs-*` and assume that's the desired package.
=> apko_tags: handle provides better

.github/workflows/mega-module.yaml
Drop k8s-diag, and in fact drop all k8s from e2e tests. Instead, just push to localhost:5000 using setup-registry
=> don't use k8s-diag

docs/data-sources/config.md, docs/data-sources/tags.md, docs/resources/build.md, go.mod, go.sum
dependabot is still on 1.22.2 so the auto update for this failed
```
go: loading module retractions for chainguard.dev/apko@v0.1.1: module chainguard.dev/apko@v0.14.5 requires go >= 1.22.3 (running go 1.22.2; GOTOOLCHAIN=local+auto)
```
https://github.com/chainguard-dev/apko/releases/tag/v0.14.6
=> bump apko to 0.14.6

.goreleaser.yml
```
$ goreleaser --version
GitVersion:    2.0.1
...
$ goreleaser check
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
=> fix goreleaser for v2

internal/provider/provider.go
For fairly large uploads, we might have expired creds during an upload retry. This forces a cred refresh after 30 minutes to ensure we aren't using expired credentials on retry.
=> Refresh creds after 30 minutes

.github/workflows/mega-module.yaml, internal/provider/config_data_source.go
It's nearly impossible to get at the config that failed if we fail to lock (because we won't have a plan to inspect), so we'll include the input config in the diagnostic details to make this at least possible.
=> If we fail to lock, include the config

docs/index.md, internal/provider/config_data_source.go, internal/provider/provider.go, internal/provider/tags_data_source_test.go
This plumbs an optional boolean through the provider to `apko_config` datasources, telling them not to fetch a new APKINDEX to solve, and instead require a locally-cached APKINDEX.
The intention with this is that we could pre-fetch an APKINDEX before sharding image builds, and avoid each shard fetching its own APKINDEX, which could introduce skew between package solutions on different shards.
=> add `plan_offline` provider option

internal/provider/reflect.go, internal/provider/reflect_test.go
We were roundtripping pointers to structs as zero-valued structs, which only worked because we didn't have any pointers to structs in apko image configurations until Layering.
=> reflect: Handle pointers in structs

docs/index.md, go.mod, go.sum, internal/provider/build.go, internal/provider/config_data_source.go, internal/provider/layering_test.go, internal/provider/layering_validation_test.go, internal/provider/provider.go
We probably shouldn't use this until `apko` support an empty `layering` object and that's plumbed through here tho.
=> Add provider-level layering support to tf-apko

.github/workflows/release.yml
Print public key upon release. This way people know which key was used
at build time to sign.
=> github: print public key

.github/workflows/mega-module.yaml, go.mod, go.sum
https://github.com/chainguard-dev/terraform-provider-apko/pull/537 and https://github.com/chainguard-dev/terraform-provider-apko/pull/545 need to be bumped together because https://github.com/chainguard-dev/apko/pull/1665/files changed `etc/ld.so.cache`
=> bump to apko 0.27.7

.goreleaser.yml, internal/provider/layering_validation_test.go, internal/provider/provider.go, internal/provider/provider_test.go, internal/provider/version_function_test.go, main.go
Setting version using ldflags is brittle, and seems not to work the way goreleaser does it today. Instead, let's just get our version from `BuildInfo` which is more reliable.
=> fix version embedding for provider version
